package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"procurement-be/graph/generated"
	"procurement-be/graph/model"
)

// Auth is the resolver for the Auth field.
func (r *mutationResolver) Auth(ctx context.Context) (*model.EmptyObject, error) {
	return &model.EmptyObject{}, nil
}

// User is the resolver for the User field.
func (r *mutationResolver) User(ctx context.Context) (*model.EmptyObject, error) {
	return &model.EmptyObject{}, nil
}

// User is the resolver for the User field.
func (r *queryResolver) User(ctx context.Context) (*model.EmptyObject, error) {
	return &model.EmptyObject{}, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
