package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"procurement-be/graph/generated"
	"procurement-be/graph/model"
	"procurement-be/pkg/product_category"
	"procurement-be/utils"
)

// Store is the resolver for the Store field.
func (r *productCategoryMutationResolver) Store(ctx context.Context, obj *model.EmptyObject, in []*model.ProductCategoryDataInput) (*model.ProductCategoryFetchResponse, error) {
	var (
		response = new(model.ProductCategoryFetchResponse)
		args     []product_category.ProductCategoryData
	)

	if err := utils.CopyObject(in, &args); err != nil {
		return nil, err
	}

	result, err := r.PkgHandler.ProductCategoryHandler.Store(ctx, args)
	if err != nil {
		return nil, err
	}

	if err = utils.CopyObject(result, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// Update is the resolver for the Update field.
func (r *productCategoryMutationResolver) Update(ctx context.Context, obj *model.EmptyObject, in []*model.ProductCategoryDataInput) (*model.ProductCategoryFetchResponse, error) {
	var (
		response = new(model.ProductCategoryFetchResponse)
		args     []product_category.ProductCategoryData
	)

	if err := utils.CopyObject(in, &args); err != nil {
		return nil, err
	}

	result, err := r.PkgHandler.ProductCategoryHandler.Update(ctx, args)
	if err != nil {
		return nil, err
	}

	if err = utils.CopyObject(result, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// Fetch is the resolver for the Fetch field.
func (r *productCategoryQueryResolver) Fetch(ctx context.Context, obj *model.EmptyObject, in *model.FetchRequestInput) (*model.ProductCategoryFetchResponse, error) {
	response := new(model.ProductCategoryFetchResponse)
	result, err := r.PkgHandler.ProductCategoryHandler.Fetch(ctx, product_category.ProductCategoryData{})
	if err != nil {
		return nil, err
	}

	if err = utils.CopyObject(result, &response); err != nil {
		return nil, err
	}
	return response, nil
}

// ProductCategoryMutation returns generated.ProductCategoryMutationResolver implementation.
func (r *Resolver) ProductCategoryMutation() generated.ProductCategoryMutationResolver {
	return &productCategoryMutationResolver{r}
}

// ProductCategoryQuery returns generated.ProductCategoryQueryResolver implementation.
func (r *Resolver) ProductCategoryQuery() generated.ProductCategoryQueryResolver {
	return &productCategoryQueryResolver{r}
}

type productCategoryMutationResolver struct{ *Resolver }
type productCategoryQueryResolver struct{ *Resolver }
