// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Data struct {
	Token    *string   `json:"token,omitempty"`
	UserData *UserData `json:"userData,omitempty"`
}

type FetchRequestInput struct {
	Role *string `json:"role,omitempty"`
	Name *string `json:"name,omitempty"`
}

type FetchResponse struct {
	IsSuccess *bool      `json:"isSuccess,omitempty"`
	Message   *string    `json:"message,omitempty"`
	Data      *UserItems `json:"data,omitempty"`
	Status    *int       `json:"status,omitempty"`
}

type LoginRequestInput struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type LoginResponse struct {
	IsSuccess *bool   `json:"isSuccess,omitempty"`
	Message   *string `json:"message,omitempty"`
	Data      *Data   `json:"data,omitempty"`
	Status    *int    `json:"status,omitempty"`
}

type Mutation struct {
}

type ProductCategoryData struct {
	ID        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
}

type ProductCategoryDataInput struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type ProductCategoryFetchResponse struct {
	IsSuccess *bool                 `json:"isSuccess,omitempty"`
	Message   *string               `json:"message,omitempty"`
	Data      *ProductCategoryItems `json:"data,omitempty"`
	Status    *int                  `json:"status,omitempty"`
}

type ProductCategoryItems struct {
	Items []*ProductCategoryData `json:"items,omitempty"`
}

type Query struct {
}

type RoleData struct {
	ID        *string `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
}

type RoleDataInput struct {
	ID   *string `json:"id,omitempty"`
	Name *string `json:"name,omitempty"`
}

type RoleFetchResponse struct {
	IsSuccess *bool      `json:"isSuccess,omitempty"`
	Message   *string    `json:"message,omitempty"`
	Data      *RoleItems `json:"data,omitempty"`
	Status    *int       `json:"status,omitempty"`
}

type RoleItems struct {
	Items []*RoleData `json:"items,omitempty"`
}

type UserData struct {
	ID        *string `json:"id,omitempty"`
	Role      *string `json:"role,omitempty"`
	Email     *string `json:"email,omitempty"`
	Name      *string `json:"name,omitempty"`
	CreatedAt *string `json:"createdAt,omitempty"`
}

type UserDataInput struct {
	ID       *string `json:"id,omitempty"`
	Role     *string `json:"role,omitempty"`
	Email    *string `json:"email,omitempty"`
	Name     *string `json:"name,omitempty"`
	Password *string `json:"password,omitempty"`
}

type UserItems struct {
	Items []*UserData `json:"items,omitempty"`
}

type Login struct {
	Access string `json:"access"`
}
